#!/bin/sh

#ensure we're in the right directory
cd /home/user/talker

echo -n "Monthly backup starting at " >> logs/backup.log
echo `date` >> logs/backup.log


# Get rid of extraneous files
rm -f files/players/backup_write
rm -f files/rooms/keys.b

# Now collect all the files together
tar cf source-backup.tar src/*.c src/*.h src/Makefile files/*.msg files/*.rooms files/banish doc/help doc/*.help doc/*.doc

# NB, we do *NOT* compress them here as that takes too long, it is done in
# the other backup script that is run as a seperate process so we don't
# pause the server for too long.
