*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=HITELLS=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*

Hitells are an easy way to differentiate in-room actions from person
to person communication.    

vt100   : probably best for a computer lab. 
ansi    : possibly best if you're dialing in, or on a good machine
vt102   : basically the same as vt100, only minor differences.
vt220   : even better than vt100 and vt102 but requires newer terminal 
sun     : for a sun workstation.
xterm   : for someone running xwindows
adm     : \
hp2392  : \\
wyse-30 : // Specific termial types that are not as common.... 
tvi912  : /

If you're unsure, try vt100 -- this seems to work for the most people.

Once on the program, you can change this setting with the HITELLS command
*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*

