
*=*=*=*=*=*=*=*=*=*=*=*=*=*=* /\/\ <> ~|~ /] =*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Special thanks to ^YBurble^N for writing the original ^yEW-too^N, ^BAthanasius^N for
 ^gSummink^N, and ^CtraP^N, ^Gastyanax^N, ^Yvallie^N, and ^HNogard^N for ^CPlayground 96^N.
*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Any problems should be refered to the Admin at: our@email.address
*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*

