*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=NEW USERS=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*

Playground is a 24 hour/day chat program based on EW-too by Simon
Marsh, aka Burble, hacked up by Neil Soveran-Charley (aka Athanasius) 
and released as Summink, then hacked to death again by Mike Bourdaa, 
(traP) Chris Allegretta (astyanax), and Hans Petersen (Nogard),
who created the current Playground 96 complete talker release. 

Once you get on the program, the easiest way to get assistance is
to type 'help' -- an alternative is to type 'lsu' and talk to one
of the people on that list.

*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*

