Welcome to Playground Version 5.O.O

(some minor updates, and most updates to SU commands, don't appear on this list
 but are credited with version upgrades. Also, older updates have been purged
 from the list. The version counting began by counting Summink's surfers 
 skeleton version as "3.O.O". Counting is Linux-style version, where the
 number is X.Y.Z.  An update of 1 X is a very signifigant, or a sum of many
 important, changes. An update of 1 Y is a major new feature or extended
 capability added. An update of 5 Z's is a major change in a feature, while
 an update of 1 Z is a minor bugfix, or small extention of an existing feature.)

5.O.O -- PLAYGROUND PUBLIC CODE RELEASE
4.9.8 -- Last minute bug fixes
4.9.7 -- Final preparations for code release
4.9.6 -- major bug fixed to item handling
4.9.5 -- noblink added!
4.9.4 -- minor typo bugs fixed
4.9.3 -- Talker name change simplified with #define TALKER_NAME
4.9.2 -- Option #define HC_ADMIN_ONE / HC_ADMIN_TWO replaced with dynamic version
4.9.1 -- boot.rooms finally deleted from the code *giggle*
4.9.O -- Preparations made for src release
4.8.32 -- case insensitive searching implemented with lso <char>
4.8.31 -- item tag bit '^^' now correctly shows up only if you have show items
4.8.28 -- lso & option added -- list by author
4.8.25 -- nobops added
4.8.24 -- colors can no longer be in an item name
4.8.23 -- typos and bugs fixed all throughout items code
4.8.22 -- Items now recycle id's
4.8.21 -- lso ! argument added to ignore the Desc: line
4.8.19 -- lso -+ flags added
4.8.18 -- fix to unpurchasable items
4.8.16 -- blocklogins -- cut down mainroom spam
4.8.15 -- show item, blockitems
4.8.14 -- drink items
4.8.13 -- bop with weilded item
4.8.12 -- ITEMS!!! They are now available to all residents -- help items
4.8.11 -- Items that give special powers exist (and are rare)
4.8.1O -- bugfix to newbies relation to items
4.8.6 -- ix -- item-examine added
4.8.5 -- sus can now delete offensive items
4.8.3 -- Items are removed at full value when deleted
4.8.2 -- Items can be weilded
4.8.1 -- Items can be worn
4.8.O -- Some items are now edible (some more than others) :P
4.7.24 -- list_objects now can list a subgroup of all available items
4.7.23 -- You can give items and money to others now
4.7.22 -- setting prices and bits on items now works
4.7.21 -- crash-bug in ungag has finally been patched
4.7.17 -- ability to view inventory
4.7.16 -- ability to buy and sell items
4.7.14 -- ability to list available items
4.7.13 -- ability to delete items
4.7.11 -- ability to create items
4.7.8 -- timeout bug fixed, now users will timeout after 4 months
4.7.5 -- builders added as a new PG job
4.7.2 -- system items added, ready to go with items now
4.7.1 -- monetary system implemented -- 50 cents + 10 for each hour of login
4.7.O -- items added to player files
4.6.9 -- No_propose added
4.6.5 -- game offers can be hilited with game_hi
4.6.4 -- news inform now works... (damn ancient summink bugs)
4.6.3 -- prs records are now kept
4.6.2 -- ability to set what you're made from
4.6.1 -- GAG (help gag)
4.6.O -- new newbie login routine
4.5.2 -- .sr actually works now *smirk*
4.5.1 -- CANCEL command added -- call off a net.engagement.
4.5.O -- Paper Rock Scissors has been implemented (help prs)
4.4.O -- Suicide is back after massive bug fixins
4.3.2 -- New command -- favorite
4.3.1 -- New editor commands -- .s and .sr       
4.3.O -- LIBRARY of ALIASES is in -- libcopy, liblist, libexam
4.2.2 -- % of time spent on the playground now kept.
4.2.1 -- After much difficulty, idling is again hazardous to your health
4.2.O -- customize -- customize your colorset
4.1.4 -- added %{first@second@third@etc} for random words chosen for aliases.
4.1.2 -- added login, logoff and recon aliases 
4.1.1 -- Alias arguments %0 for all arguments, %# for a specific word
4.1.O -- define an alias!
4.O.1 -- blockdesc -- ignore room descriptions.
4.O.O -- COLORS are now active on the playground!
3.5.O -- reconnection fix -- some values will be saved.
3.4.1 -- You can now tell to other people's friends! type HELP FRIENDTELL
3.4.O -- You can now block friendmail with BLOCKFMAIL
3.3.2 -- MAIL POST FRIENDS (sorry, but this was HARD to do)
3.3.1 -- Auto-backups installed to go off at about 1 am every day.
3.3.O -- Examine and Finger now shows your email address and/or site, according
         to how you set the TOGGLE. Default is private for both.
3.2.O -- nobeep has been installed
3.1.2 -- idle times now appear on the idle command
3.1.O -- channels included, gossip channel removed. (type help chan)
